#服务的端口号
server:
  port: 2010

#服务的名称
spring:
  application:
    name: demo1
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 1000
      max-wait: -1
      max-idle: 1
    database: 1
    timeout: 2000